version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  helloworld:
    lang: node12
    handler: ./helloworld
    image: revolunet/helloworld:latest
  ascii:
    lang: node12
    handler: ./ascii
    image: revolunet/ascii:latest
  dumdum:
    lang: node12
    handler: ./dumdum
    image: revolunet/dumdum:latest


